/**
 * One-off: self-host the Google Fonts the site uses (Poppins, weights 100–600)
 * so no visitor IP is sent to Google's CDN (DSGVO) and fonts load same-origin.
 * Fetches the css2 sheet with a modern UA (→ woff2), keeps the latin +
 * latin-ext subsets (covers DE + EN incl. umlauts/ß), downloads each woff2 into
 * assets/fonts/, and writes assets/fonts/fonts.css with local URLs.
 *
 * Poppins carries ALL three body/display registers since the thermal redesign:
 * 100/200 = thin display caps (headlines), 300–600 = body/UI. The label mono
 * (JetBrains Mono) is appended by scripts/fetch-fonts-extra.mjs — run that
 * AFTER this script (this one rewrites fonts.css from scratch).
 *
 * Network goes through `curl` (which honours the environment HTTPS proxy);
 * Node's global fetch does not. Re-run to refresh. Requires network to
 * Google Fonts.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";

const URL = "https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600&display=swap";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const KEEP = new Set(["latin", "latin-ext"]);

const curlText = (url) => execFileSync("curl", ["-sS", "-A", UA, url], { encoding: "utf8", maxBuffer: 1e8 });
const curlBin = (url) => execFileSync("curl", ["-sS", "-A", UA, url], { maxBuffer: 1e8 });

const css = curlText(URL);

// Split into "/* subset */ @font-face {...}" units.
const units = css.split(/\/\*\s*/).slice(1); // each starts with "subset */ @font-face..."
let out = "/* Self-hosted Poppins (latin, latin-ext) — generated by scripts/fetch-fonts.mjs */\n";
let count = 0;
mkdirSync("assets/fonts", { recursive: true });

for (const u of units) {
  const subset = u.slice(0, u.indexOf(" */")).trim();
  if (!KEEP.has(subset)) continue;
  const block = u.slice(u.indexOf("@font-face"));
  const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
  const style = (block.match(/font-style:\s*(\w+)/) || [])[1];
  const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1];
  const url = (block.match(/src:\s*url\(([^)]+)\)/) || [])[1];
  const range = (block.match(/unicode-range:\s*([^;]+);/) || [])[1];
  if (!fam || !url) continue;
  const name = `${fam.toLowerCase()}-${weight}-${style}-${subset}.woff2`;
  const buf = curlBin(url);
  writeFileSync(`assets/fonts/${name}`, buf);
  out += `@font-face{font-family:'${fam}';font-style:${style};font-weight:${weight};font-display:swap;`
    + `src:url('/assets/fonts/${name}') format('woff2');unicode-range:${range};}\n`;
  count++;
  console.log(`${name}  ${(buf.length / 1024).toFixed(1)}KB`);
}
writeFileSync("assets/fonts/fonts.css", out);
console.log(`\n${count} faces → assets/fonts/fonts.css`);
